spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234abcd
    url: jdbc:mysql://localhost:3306/yessUni

server:
  port: 8080
  servlet:
    session:
      timeout: 86400
    #应用的上下文路径，也可以称为项目路径，是构成url地址的一部分.所有请求地址匹配路径添加/api
    context-path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  #开启mybatis-plus的逻辑删除
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)